name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++17
      uses: actions/setup-cpp@v1
      with:
        compiler: 'gcc'
        cpp-version: '17'

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
      continue-on-error: true

    - name: Store test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/Testing

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: build/*.exe
